### ISSUE TITLE
Error appear when a player change his password

### ISSUE THREAD

**Issue by CryLegende** [AuthMe/UnregisterMe#2]
https://hasteb.in/yayubuwi.rb

PaperSpigot 1.8.8
Latest build of UnregisterMe

**Comment by CryLegende** [comment]
I realize that I did not give enough information sorry
Error: https://pastebin.com/raw/Ja8yTHEr
It appears when a player changes their password, the password is changed but the confirmation message does not appear in the chat

Same error with PaperSpigot 1.12

**Comment by sgdc3** [comment]
Fixed!
